FROM rust:latest AS builder

RUN cargo install cargo-afl

ADD . /kdl-rs
WORKDIR /kdl-rs/fuzz
RUN cargo afl build --release

FROM --platform=linux/amd64 ubuntu:22.04
COPY --from=builder /kdl-rs/fuzz/target/release/fuzz /fuzz
COPY --from=builder /kdl-rs/fuzz/in /in
